# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
# - task: PowerShell@2
#   inputs:
#     targetType: 'inline'
#     script: |
#       cd src
#       dotnet restore
#       dotnet publish --no-restore --configuration Release

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/src'
    zipAfterPublish: True

#this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/src' 
    artifactName: 'myWebsiteName'

- task: Docker@2
  inputs:
    containerRegistry: 'braindevopstraining'
    repository: 'dotnet-demo'
    command: 'buildAndPush'
    Dockerfile: '/build/Dockerfile'